INSERT INTO dba_relationships VALUES ('accounts','Update Splits',"UPDATE splits SET account=REPLACE('$name',' ','_') WHERE account=REPLACE('$$name',' ','_')");
INSERT INTO dba_relationships VALUES ('accounts','Update Transactions (Main)',"UPDATE transactions SET account=REPLACE('$name',' ','_') WHERE account=REPLACE('$$name',' ','_')");
INSERT INTO dba_relationships VALUES ('accounts','Update Transactions (Source)',"UPDATE transactions SET source_account=REPLACE('$name',' ','_') WHERE source_account=REPLACE('$$name',' ','_')");
INSERT INTO dba_relationships VALUES ('accounts','Update Transactions (Target)',"UPDATE transactions SET target_account=REPLACE('$name',' ','_') WHERE target_account=REPLACE('$$name',' ','_')");
INSERT INTO dba_relationships VALUES ('categories','Delete/Update Funds (Exp)',"DELETE/UPDATE funds SET default_expense_cat=NULL WHERE default_expense_cat='$$name'");
INSERT INTO dba_relationships VALUES ('categories','Delete/Update Funds (Inc)',"DELETE/UPDATE funds SET default_income_cat=NULL WHERE default_income_cat='$$name'");
INSERT INTO dba_relationships VALUES ('categories','Delete/Update Payees',"DELETE/UPDATE payees SET default_cat=NULL WHERE default_cat='$$name'");
INSERT INTO dba_relationships VALUES ('categories','Delete/Update Splits',"DELETE/UPDATE splits SET category='-none-' WHERE category='$$name'");
INSERT INTO dba_relationships VALUES ('categories','Delete/Update Transactions',"DELETE/UPDATE transactions SET category='-none-' WHERE category='$$name'");
INSERT INTO dba_relationships VALUES ('categories','Update Funds (Exp)',"UPDATE funds SET default_expense_cat='$name' WHERE default_expense_cat='$$name'");
INSERT INTO dba_relationships VALUES ('categories','Update Funds (Inc)',"UPDATE funds SET default_income_cat='$name' WHERE default_income_cat='$$name'");
INSERT INTO dba_relationships VALUES ('categories','Update Payees',"UPDATE payees SET default_cat='$name' WHERE default_cat='$$name'");
INSERT INTO dba_relationships VALUES ('categories','Update Splits',"UPDATE splits SET category='$name' WHERE category='$$name'");
INSERT INTO dba_relationships VALUES ('categories','Update Transactions',"UPDATE transactions SET category='$name' WHERE category='$$name'");
INSERT INTO dba_relationships VALUES ('funds','Delete/Update Payees',"DELETE/UPDATE payees SET default_fund=NULL WHERE default_fund='$$name'");
INSERT INTO dba_relationships VALUES ('funds','Delete/Update Splits',"DELETE/UPDATE splits SET fund='TBD' WHERE fund='$$name'");
INSERT INTO dba_relationships VALUES ('funds','Delete/Update Transactions',"DELETE/UPDATE transactions SET fund='TBD' WHERE fund='$$name'");
INSERT INTO dba_relationships VALUES ('funds','Update Payees',"UPDATE payees SET default_fund='$name' WHERE default_fund='$$name'");
INSERT INTO dba_relationships VALUES ('funds','Update Splits',"UPDATE splits SET fund='$name' WHERE fund='$$name'");
INSERT INTO dba_relationships VALUES ('funds','Update Transactions',"UPDATE transactions SET fund='$name' WHERE fund='$$name'");
INSERT INTO dba_relationships VALUES ('payees','Transactions',"  SELECT * FROM transactions WHERE payee='$name'");
INSERT INTO dba_relationships VALUES ('payees','Update Transactions',"UPDATE transactions SET payee='$name' WHERE payee='$$name'");
INSERT INTO dba_relationships VALUES ('transactions','Delete Splits',"DELETE FROM splits WHERE account='$account' AND transact_seq_no=$seq_no");
INSERT INTO dba_relationships VALUES ('transactions','Splits',"SELECT * from splits WHERE transact_seq_no=$seq_no");
