#!/bin/bash
# Because this script is for the online server only, it is safe to
# determine the setting of $root_dir from the local script path.
script_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
root_dir="$(php $script_dir/../root_dir.php)"
if [ -d "$root_dir" ] && [ "${root_dir:0:5}" == "/home" ]; then
    du $root_dir > $root_dir/maintenance/disc_storage.txt 2>/dev/null
    php $root_dir/public_html/common_scripts/check_disc_storage.php

    # The variable $mailbox_list is optional, but to use it, the script must be invoked
    # by a 'source' directive with the variable preset.
    if [ "$mailbox_list" != "" ]; then
        php $root_dir/public_html/common_scripts/check_email_storage.php $domain $mailbox_list
    fi
fi
