#!/bin/bash
script_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source $script_dir/set_path_vars
if [ "$location" == "real" ]; then

    # Report site disc storage
    used_storage=$(du -k $root_dir | tail -n 1 | awk '{print $1}')
    ssh -i ~/.ssh/andperry2_rsa -p 88 andper1@cp160174.hpdns.net "/home/andper1/maintenance/report_disc_storage $site_path $used_storage"

    # Report email storage
    mailbox_data=$($phpcmd $script_dir/php/get_email_storage_data.php $site_path)
    ssh -i ~/.ssh/andperry2_rsa -p 88 andper1@cp160174.hpdns.net "/home/andper1/maintenance/report_email_storage $site_path $mailbox_data"
fi
