#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $script_dir/set_path_vars
find $root_dir -name error_log -exec rm {} \;
wget -q -O - $base_url/common_scripts/display_debug_log.php?clear > /dev/null
