#!/bin/bash
action=$1
script_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source $script_dir/set_path_vars
if [ "$location" == "real" ]; then
    if [ "$action" == "" ]; then
        # The variable $action is optional on calling the script, but can be
        # updated here if not yet set.
        action=`wget -q -O - https://remote.andperry.com/crontab_action.php`
    fi

    if [ "$action" == "save" ]; then
        echo "Saving crontab ..."
        crontab -l > $root_dir/maintenance/crontab.txt
        php $root_dir/public_html/common_scripts/crontab_save.php $site_path
        rm $root_dir/maintenance/crontab.txt
    elif [ "$action" == "restore" ]; then
        echo "Restoring crontab ..."
        wget -q -O - https://remote.andperry.com/get_crontab.php?site_path=$site_path > $root_dir/maintenance/crontab.txt
        if [ -e "$root_dir/maintenance/crontab.txt" ]; then
            crontab $root_dir/maintenance/crontab.txt
            rm $root_dir/maintenance/crontab.txt
            crontab -l
        fi
    fi
fi
