#!/bin/bash
# This file must be invoked via the 'source' directive with all required variables preset
if [ -d "/home/$cpuser" ]
then
    wget -q -O - https://$domain/common_scripts/optimise_databases.php
else
    wget -q -O - http://home.andperry.com/$site_path/common_scripts/optimise_databases.php?site=$site_path
fi
