#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $script_dir/set_path_vars
themes_dir="$root_dir/public_html/wp-content/themes"
source "$root_dir/public_html/common_scripts/bash/set_default_theme"
echo "Default theme = $default_theme"

if [ -d "$themes_dir" ]; then
    cd $themes_dir
    for theme in twenty*
    do
        if [ "$theme" != "$default_theme" ]; then
            if [ -d  "$themes_dir/$theme" ]; then
                echo "  Removing theme $theme"
                rm -rf "$themes_dir/$theme"
            elif [ -L  "$themes_dir/$theme" ]; then
                echo "  Unlinking theme $theme"
                rm "$themes_dir/$theme"
            fi
        fi
    done
fi
