#!/bin/bash
script_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source $script_dir/set_path_vars
if [ "$location" == "real" ]; then
    echo "Re-caching pages ..."
    php $root_dir/public_html/common_scripts/recache_all_pages.php
fi
