#!/bin/bash
# This script must be invoked from the calling script using the 'source'
# directive and with the variables $root_dir and $site_path preset.
wget -q -O - https://remote.andperry.com/get_crontab.php?site_path=$site_path > $root_dir/maintenance/crontab.txt
if [ -e "$root_dir/maintenance/crontab.txt" ]
then
    crontab $root_dir/maintenance/crontab.txt
    rm $root_dir/maintenance/crontab.txt
    crontab -l
fi
