#!/bin/bash
# This script must be invoked from the calling script using the 'source'
# directive and with the variables $phpcmd and $sitepath preset.
if [ "$phpcmd" == "" ]; then
    echo "PHP command variable not specified"
    exit
fi
if [ "$sitepath" == "" ]; then
    echo "Site Path variable not specified"
    exit
fi
cd $sitepath
echo $(date)." - $sitepath"
cmd="$phpcmd -d error_reporting=E_ERROR ./common_scripts/wp-cli/wp-cli.phar cron event run --due-now"
if [ -f "/Config/localhost.php" ]; then
    # Allow root access on local host
    cmd="$cmd --allow-root"
fi
$cmd
