#!/bin/bash
# This script is called (normally via SSH to a remote server) to run the mysql
# command on a given database.
#
# The following parameters are mandatory:
# 1 - Hostname
# 2 - Username
# 3 - Password
# 4 - Database
# 5 - Source script file (without the .sql extension)
#
# Any further parameters will go directly as options in the mysqldump command.
#
host=$1
user=$2
password=$3
dbname=$4
sql_script=$5
shift 5
options=$@
script_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
root_dir="$(php $script_dir/../root_dir.php)"
mysql --host=$host --user=$user --password=$password $options -D $dbname < $root_dir/mysql_backup/$dbname/$sql_script.sql
