#!/bin/bash
# Because this script is for the online server only, it is safe to
# determine the settings of $root_dir and $site_path from the local
# script path.
script_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
root_dir="$(php $script_dir/../root_dir.php)"
site_path="$(php $script_dir/../local_site_dir.php)"
if [ -d "$root_dir" ] && [ "${root_dir:0:5}" == "/home" ]; then
    if [ "$action" == "" ]; then
        action=`wget -q -O - https://remote.andperry.com/crontab_action.php`
    fi

    # The variable $action is optional, but to use it, the script must be invoked
    # by a 'source' directive with the variable preset.
    if [ "$action" == "save" ]; then
        echo "Saving crontab ..."
        crontab -l > $root_dir/maintenance/crontab.txt
        php $root_dir/public_html/common_scripts/save_crontab.php $site_path
        rm $root_dir/maintenance/crontab.txt
    elif [ "$action" == "restore" ]; then
        echo "Restoring crontab ..."
        wget -q -O - https://remote.andperry.com/get_crontab.php?site_path=$site_path > $root_dir/maintenance/crontab.txt
        if [ -e "$root_dir/maintenance/crontab.txt" ]; then
            crontab $root_dir/maintenance/crontab.txt
            rm $root_dir/maintenance/crontab.txt
            crontab -l
        fi
    fi
fi
