#!/bin/bash
# This script is normally for use by Bash scripts within the 'maintenance'
# directory of a given site, and is used for setting various common variables.
# It must be invoked via a 'source' directive. Handling is slightly different
# for a local server, where a single 'common_scripts' directory is shared by
# all sites.
#
saved_script_dir=$script_dir
script_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
if [ "${script_dir:0:5}" == "/home" ]; then
    # Online Server
    location="real"
    phpcmd="/opt/cpanel/ea-php84/root/usr/bin/php -d error_reporting=E_ERROR"
    site_path="$($phpcmd $script_dir/../local_site_dir.php)"
    root_dir="$($phpcmd $script_dir/../root_dir.php)"
    cpuser="$($phpcmd $script_dir/../cpanel_user.php)"
    online_domain="$($phpcmd $script_dir/../main_domain.php)"
else
    # Local Server
    location="local"
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Extract the site path, allowing for all possible variants of the directory path
    temp=${script_dir/\/media\/Data\/Users\/Common\/Documents\/WebSite\/Sites\//}
    temp=${temp/\/media\/Data\/www\/Sites\//}
    temp=${temp/\/media\/Data\/www\//}
    site_path=${temp/\/public_html\/common_scripts\/bash/}

    source /Config/php_pars
    root_dir="$($phpcmd $script_dir/../root_dir.php $site_path)"
    cpuser="$($phpcmd $script_dir/../cpanel_user.php $site_path)"
    online_domain="$($phpcmd $script_dir/../main_domain.php $site_path)"
fi
script_dir=$saved_script_dir
